'use strict';

const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { spawnSync } = require('node:child_process');
const test = require('node:test');
const { parseFrontmatter, parseScalar, parseYaml } = require('../scripts/lib/parsers');

const ROOT = path.join(__dirname, '..');

function withTempDirectory(run) {
    const tempRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'kac-parser-'));
    try {
        return run(tempRoot);
    } finally {
        fs.rmSync(tempRoot, { recursive: true, force: true });
    }
}

function schemaYamlExamples() {
    const schema = fs.readFileSync(path.join(ROOT, 'data', '_schema.md'), 'utf8');
    return [...schema.matchAll(/```yaml\n([\s\S]*?)\n```/g)].map(match => match[1]);
}

test('frontmatter parses documented schema scalars and comments from a CRLF copy', () => {
    withTempDirectory(tempRoot => {
        const [primaryExample, , authorityExample] = schemaYamlExamples();
        const primaryPath = path.join(tempRoot, 'primary.md');
        const authorityPath = path.join(tempRoot, 'authority.md');
        fs.writeFileSync(primaryPath, `${primaryExample}\n## Summary\nBody`.replace(/\n/g, '\r\n'));
        fs.writeFileSync(authorityPath, `${authorityExample}\n## Regulations\n\n- iso-27001`.replace(/\n/g, '\r\n'));

        const primaryParsed = parseFrontmatter(fs.readFileSync(primaryPath, 'utf8'));
        assert.equal(primaryParsed.frontmatter.id, 'access-control');
        assert.equal(primaryParsed.frontmatter.name, 'Access Control');
        assert.equal(primaryParsed.frontmatter.status, 'active');
        assert.deepEqual(primaryParsed.frontmatter.search_terms, ['authorization', 'permissions']);
        assert.equal(primaryParsed.body, '## Summary\nBody');

        const authorityParsed = parseFrontmatter(fs.readFileSync(authorityPath, 'utf8'));
        assert.equal(authorityParsed.frontmatter.id, 'iso');
        assert.equal(authorityParsed.frontmatter.website, 'https://iso.org/');
    });
});

test('frontmatter decodes supported quoted scalars without treating hashes as comments', () => {
    const parsed = parseFrontmatter([
        '---',
        'title: "The \\"Quoted\\" #1" # display name',
        "owner: 'Sam''s Reference' # apostrophe",
        'enabled: true # frontmatter remains string-valued',
        'aliases:',
        '  - "Dollar $& value" # literal replacement characters',
        '  # list comment: colons do not become keys',
        '',
        '  - value#fragment',
        '---',
        'Body'
    ].join('\n'));

    assert.equal(parsed.frontmatter.title, 'The "Quoted" #1');
    assert.equal(parsed.frontmatter.owner, "Sam's Reference");
    assert.equal(parsed.frontmatter.enabled, 'true');
    assert.deepEqual(parsed.frontmatter.aliases, ['Dollar $& value', 'value#fragment']);
    assert.equal(parsed.frontmatter['# list comment'], undefined);
});

test('configuration parsing decodes quotes, strips comments, and retains typed booleans', () => {
    const parsed = parseYaml([
        'name: "The \\"Quoted\\" Reference" # generated by init',
        "single: 'Sam''s Reference'",
        'literal_hash: value#fragment',
        'enabled: true # remains boolean',
        'disabled: false',
        'empty_list: [] # remains an array',
        'labels:',
        '  - "Control: Primary"',
        "  - 'Owner: Sam''s group'"
    ].join('\r\n'));

    assert.equal(parsed.name, 'The "Quoted" Reference');
    assert.equal(parsed.single, "Sam's Reference");
    assert.equal(parsed.literal_hash, 'value#fragment');
    assert.equal(parsed.enabled, true);
    assert.equal(parsed.disabled, false);
    assert.deepEqual(parsed.empty_list, []);
    assert.deepEqual(parsed.labels, ['Control: Primary', "Owner: Sam's group"]);
    assert.equal(parseScalar('"Mapping: value" # comment', false), 'Mapping: value');
    assert.throws(() => parseYaml('name: "unterminated'), /Invalid YAML scalar on line 1: Unterminated double-quoted scalar/);
});

test('initializer output round-trips quoted and replacement-like labels', () => {
    withTempDirectory(tempRoot => {
        const target = path.join(tempRoot, 'initialized');
        const values = {
            name: 'The "Quoted" \\ Reference #1',
            primary: 'Checks $& Controls',
            container: 'Plans $` Catalogs',
            authority: "Owners' Groups",
            secondary: 'Links $$ Records'
        };
        const result = spawnSync(process.execPath, [
            path.join(ROOT, 'scripts', 'init.js'), target, '--defaults',
            '--name', values.name,
            '--short-name', 'quoted-reference',
            '--url', 'https://example.com/reference/',
            '--repo', 'https://github.com/example/quoted-reference',
            '--primary', values.primary,
            '--container', values.container,
            '--authority', values.authority,
            '--secondary', values.secondary
        ], { cwd: ROOT, encoding: 'utf8' });

        assert.equal(result.status, 0, result.stderr || result.stdout);
        const config = parseYaml(fs.readFileSync(path.join(target, 'project.yml'), 'utf8'));
        assert.equal(config.name, values.name);
        assert.equal(config.entities.primary.name, 'Checks $& Control');
        assert.equal(config.entities.primary.plural, values.primary);
        assert.equal(config.entities.container.name, 'Plans $` Catalog');
        assert.equal(config.entities.container.plural, values.container);
        assert.equal(config.entities.authority.name, "Owners' Group");
        assert.equal(config.entities.secondary.plural, values.secondary);
        assert.equal(config.nav.find(item => item.id === 'containers').label, values.container);
        assert.equal(config.nav.find(item => item.id === 'primaries').label, values.primary);

        const generatedParser = require(path.join(target, 'scripts', 'lib', 'parsers.js'));
        const generatedConfig = generatedParser.parseYaml(fs.readFileSync(path.join(target, 'project.yml'), 'utf8'));
        assert.equal(generatedConfig.name, values.name);
        assert.equal(generatedConfig.entities.secondary.plural, values.secondary);

        const validation = spawnSync(process.execPath, ['scripts/validate.js'], {
            cwd: target,
            encoding: 'utf8'
        });
        assert.equal(validation.status, 0, validation.stderr || validation.stdout);
    });
});
